using Devices.Application.Dtos;
using Devices.Application.Services;
using Devices.Domain.Enums;
using Microsoft.AspNetCore.Mvc;

namespace Devices.Api.Controllers;

[ApiController]
[Route("api/devices")]
[Produces("application/json")]
public class DevicesController : ControllerBase
{
	private readonly DeviceService _deviceService;

	public DevicesController(DeviceService deviceService)
	{
		_deviceService = deviceService;
	}

	[HttpPost]
	[EndpointSummary("Creates a new device")]
	[EndpointDescription("Id and creation time are generated by the server. If state is omitted, the device is created as Available.")]
	[ProducesResponseType(typeof(DeviceResponse), StatusCodes.Status201Created)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
	public async Task<ActionResult<DeviceResponse>> Create([FromBody] CreateDeviceRequest request)
	{
		var device = await _deviceService.CreateDeviceAsync(request);
		return CreatedAtAction(nameof(GetById), new { id = device.Id }, device);
	}

	[HttpGet("{id:guid}")]
	[EndpointSummary("Gets a device by id")]
	[ProducesResponseType(typeof(DeviceResponse), StatusCodes.Status200OK)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
	public async Task<ActionResult<DeviceResponse>> GetById(Guid id)
	{
		var device = await _deviceService.GetDeviceByIdAsync(id);
		return Ok(device);
	}

	[HttpGet]
	[EndpointSummary("Lists devices")]
	[EndpointDescription("Optionally filtered by brand and/or state. Returns an empty list when nothing matches.")]
	[ProducesResponseType(typeof(IReadOnlyList<DeviceResponse>), StatusCodes.Status200OK)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
	public async Task<ActionResult<IReadOnlyList<DeviceResponse>>> GetAll([FromQuery] string? brand, [FromQuery] DeviceState? state)
	{
		var devices = await _deviceService.GetAllDevicesAsync(brand, state);
		return Ok(devices);
	}

	[HttpPut("{id:guid}")]
	[EndpointSummary("Fully updates a device")]
	[EndpointDescription("Name and brand cannot be changed while the device is in use. Creation time cannot be updated.")]
	[ProducesResponseType(typeof(DeviceResponse), StatusCodes.Status200OK)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
	public async Task<ActionResult<DeviceResponse>> Update(Guid id, [FromBody] UpdateDeviceRequest request)
	{
		var device = await _deviceService.UpdateDeviceAsync(id, request);
		return Ok(device);
	}

	[HttpPatch("{id:guid}")]
	[EndpointSummary("Partially updates a device")]
	[EndpointDescription("Only the fields sent are changed. Name and brand cannot be changed while the device is in use.")]
	[ProducesResponseType(typeof(DeviceResponse), StatusCodes.Status200OK)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
	public async Task<ActionResult<DeviceResponse>> Patch(Guid id, [FromBody] PatchDeviceRequest request)
	{
		var device = await _deviceService.PatchDeviceAsync(id, request);
		return Ok(device);
	}

	[HttpDelete("{id:guid}")]
	[EndpointSummary("Deletes a device")]
	[EndpointDescription("Devices that are in use cannot be deleted.")]
	[ProducesResponseType(StatusCodes.Status204NoContent)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
	[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
	public async Task<IActionResult> Delete(Guid id)
	{
		await _deviceService.DeleteDeviceAsync(id);
		return NoContent();
	}
}
